LOG_LEVEL: INFO

# ######################################################################################################
# # https://docs.sqlalchemy.org/en/13/core/engines.html
DATABASE:
  DRIVER: mysql+pymysql
  NAME: thcloud
  HOST: 127.0.0.1
  PORT: 3306
  USERNAME: root
  PASSWORD: root
  QUERY:
    charset: utf8mb4


HOST: 0.0.0.0
PORT: 8000

MINIO:
  ADDRESS: 192.168.14.12:9000
  ADMIN: admin
  PASSWORD: admin123
